# Everything after a # is a comment and ignored

# Server stuff
name: Test Server
maxplayers: 500

path: world

# World simulation stuff
world:
  # Change gamemode by doing /gamerule spawnGamemode <gamemode>
  seed: 1234 # 32 bit seed
  netherscale: 16
  chunkloadingrange: 3 # recommended: 3

# Client components/mods
components:
  - /vanilla/index.js

# Terrain generators
generators:
  # All generators have these options:
  # default -> normal terrain generation
  # flat -> normal biomes and foliage, structures, etc but all terrain is the same height (no oceans)
  # perlin -> akin to java amplified, but goes up & down infinitely and is really smooth
  # fill -> no air besides any naturally forming caves. Also means no grass and no oceans

  # You may force a dimension to generate like another by specifying the dimension to copy before a slash
  # (e.g you could set overworld to nether/flat)

  # You may also set any dimension to "void", where no blocks will naturally generate whatsoever

  # Overworld also has:
  # superflat -> 1 layer of grass, 3 layers of dirt, stone below that. No features whatsoever
  overworld: default

  # Nether also has:
  # superflat -> netherrack below Y=-128 and above Y=128, air in between
  # opensky -> no nether ceiling, giving a similar shape to the overworld
  nether: default

  # flat is almost the same as void
  end: default

  # void is a special dimension, acts as a "spare" dimension for things like map-making
  # The only way to get there is with /tp
  # It doesnt have any of its own generators, so it must borrow from another dimension
  void: void

permissions:
  # Allow anyone to use /kill to kill themselves
  suicide: true

  # Allow anyone to chat (disabling will only allow moderators and above to use chat)
  chat: true

  # Allow green text in chat by prefixing your messages with >
  greentext: true

  # Allow moderators to use /give, /setblock, etc...
  mod_cheat: true

  # Maximum blocks you can /fill at once
  max_fill: 16777216

  # Default permission level when joining for the first time
  # 4 = op (NOT RECOMMENDED)
  # 3 = mod
  # 2 = normal
  # 1 = spectate (allowed to walk around but not place/break blocks or summon/damage entities)
  # 0 = not allowed to join (whitelist)
  # Individual player permissions can be changed with /perm <username> <level>
  default: 2


port: 27277
# Key and certificate files for encrypted server (recommended). Paths are relative to parent of server folder
# Empty values will attempt to use a self signed certificate for localhost
key: ""
cert: ""

# Voice chat to players up to this many blocks away in-game
# 0 to disable
# Chat using the Enter ↵ key
proximitychat: 32
# Show everyone's health on the TAB menu and server page
showhealth: true
# Webhook url for discord chat integration (optional)
webhook:
# Display a different discord avatar and username for each player when chatting
webhook_profiles: true
# Home page will count how often this word is said in chat
magic_word: hi

icon: /img/beacon.png
motd:
  - One of the servers of all time
  - Potassium-free!
  - New motd every day! (maybe)
  - Zero warranty!
  - One must imagine sisyphus happy
  - And I have become death, the destroyer of worlds
  - MOTD unavailable
  - <img src=x onerror=xss()/>

# info displayed on the banned notice screen
ban_appeal_info: 

# Do not touch this section for multiplayer servers unless you ABSOLUTELY know what you're doing!
# You have been warned!
socket:
  # Check for suspicious movement packets
  # Recommended: true
  # Setting to false will allow any player to move at any speed and teleport anywhere without creative or operator
  # which may allow any player to load an excessive amount of chunks and crash the server
  movementchecks: true

  # Blocks player can stray before being rubberbanded
  movementcheckmercy: 10

  # Maximum queued data on a single socket in MB. 0 = no limit (dangerous). Recommended: 16
  backpressure: 16